{% set author = "lloyd" %}
{% set name = "yajl" %}
{% set version = "2.1.0" %}
{% set sha256sum = "3f059e541c276598aeb668796e6426fc0034d98cb6528cd7f379c217414d9ff3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ author }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cmake 3.*
    - python  # [win]

test:
  requires:
    - pkg-config  # [unix]

  commands:
    - echo "{}" | json_reformat  # [unix]
    - echo "{}" | json_verify  # [unix]

    - test -f ${PREFIX}/include/{{ name }}/{{ name }}_common.h  # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}_s.a  # [unix]
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so  # [linux]
    - pkg-config --cflags --libs {{ name }}  # [unix]

    - if not exist %PREFIX%\\Library\\include\\{{ name }}\\{{ name }}_common.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}_s.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}.dll exit 1  # [win]

    - conda inspect linkages -p $PREFIX {{ name }}  # [unix]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: https://lloyd.github.io/yajl/
  license: ISC
  license_file: COPYING
  summary: Yet Another JSON Library
  description: |
    YAJL is a small event-driven (SAX-style) JSON parser written in ANSI C, and
    a small validating JSON generator. YAJL is released under the ISC license.
  dev_url: https://github.com/lloyd/yajl

extra:
  recipe-maintainers:
    - rmax
